# Run this command to install: docker-compose up -d --build
# TODO: add dvwa service at /php/dvwa
version: "3.8"
services:
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 7001:80
    volumes:
      - ./docker-volume/log/:/var/log/nginx/

  php:
    build: ./php/
    container_name: php
    expose:
      - 9000
    volumes:
      - ./docker-volume/html/:/var/www/html/

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    volumes:
      - ./docker-volume/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydbuser
      MYSQL_PASSWORD: mydbpwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 9080:80
    environment:
      PMA_HOST: mysql

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - 9082:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: mydbuser
      MYSQL_PASSWORD: mydbpwd
      MYSQL_DB: mydb
    volumes:
      - ./docker-volume/dvwa/vulnerabilities/:/var/www/html/vulnerabilities/  # 映射主機上的 ./dvwa 目錄到容器內的 /var/www/html
